services:
  alimafi-cv:
    container_name: alimafi-cv
    build: .
    expose:
      - 80
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.cv.rule=Host(`cv.alimafi.ir`)
      - traefik.http.routers.cv.entrypoints=web
      - traefik.http.routers.cv.tls=false
      #- traefik.http.routers.cv.tls.certresolver=letsencrypt
      - traefik.http.routers.cv.priority=1
      - traefik.http.services.cv.loadbalancer.server.port=80


    
networks:
  traefik-network:
    external: true
