name: üìÑ‚ú® Release CV

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: üõ†Ô∏è Checkout Repository
        uses: actions/checkout@v4

      - name: üöÄ Set Up Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: üèóÔ∏è Build Resume in LaTeX
        run: |
          tectonic -X build

      - name: ‚ú® Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/AliMafi/AliMafi.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: üöÄ Set Up Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: üèóÔ∏è Build Resume in LaTeX
        run: |
          tectonic -X build

      - name: Send PDF file to server
        run: |
          scp -P ${{ secrets.DEPLOY_PORT }} \
            ./build/AliMafi/AliMafi.pdf ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.REMOTE_PATH }}/html/

      - name: Run deploy commands on server
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.DEPLOY_PORT }} \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<'EOF'
              cd ${{ secrets.REMOTE_PATH }}
              docker compose pull
              docker compose down
              docker compose up -d
              docker image prune -f
          EOF
